image: docker:stable
services:
  - docker:stable-dind

stages:
  - build
  - release

build:
  stage: build
  script:
    - apk add make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make all REGISTRY=${CI_REGISTRY_IMAGE}
    - make push REGISTRY=${CI_REGISTRY_IMAGE}
    - make push-short REGISTRY=${CI_REGISTRY_IMAGE}
    - make push-latest REGISTRY=${CI_REGISTRY_IMAGE}

release:
  stage: release
  only:
    - tags
  script:
    - apk add make
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

    - make all VERSION="${CI_COMMIT_TAG}"
    - make push VERSION="${CI_COMMIT_TAG}"
    - make push-short VERSION="${CI_COMMIT_TAG}"
    - make push-latest VERSION="${CI_COMMIT_TAG}"
