services:
  - docker:stable-dind

stages:
  - build
  - release

build:
  stage: build
  image: docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make all REGISTRY=${CI_REGISTRY_IMAGE}
    - make push REGISTRY=${CI_REGISTRY_IMAGE}
    - make push-short REGISTRY=${CI_REGISTRY_IMAGE}

release:
  stage: release
  image: docker:dind
  only:
    - tags
  script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

    - make all VERSION="$(CI_COMMIT_TAG)"
    - make push VERSION="$(CI_COMMIT_TAG)"
    - make push-short VERSION="$(CI_COMMIT_TAG)"
